// Lexegen autogenerated definition file - do not edit!

enum {
    err_end_of_input = -1,
    predef_pat_default = 0,
    pat_escape_quot,
    pat_escape_rev_sol,
    pat_escape_sol,
    pat_escape_b,
    pat_escape_f,
    pat_escape_n,
    pat_escape_r,
    pat_escape_t,
    pat_escape_unicode,
    pat_escape_other,
    pat_string_seq,
    pat_string_close,
    pat_string_nl,
    pat_null,
    pat_true,
    pat_false,
    pat_decimal,
    pat_neg_decimal,
    pat_real,
    pat_comment,
    pat_c_comment,
    total_pattern_count,
};

enum {
    sc_initial = 0,
    sc_string,
};
