/* Lexegen autogenerated definition file - do not edit! */

enum {
    err_end_of_input = -1,
    predef_pat_default = 0,
    pat_null,
    pat_true,
    pat_false,
    pat_decimal,
    pat_neg_decimal,
    pat_real,
    pat_ws_with_nl,
    pat_other_value,
    pat_amp,
    pat_lt,
    pat_gt,
    pat_apos,
    pat_quot,
    pat_entity,
    pat_dcode,
    pat_hcode,
    pat_string_seq_quot,
    pat_string_close_quot,
    pat_string_seq_apos,
    pat_string_close_apos,
    pat_string_other,
    pat_string_nl,
    pat_name,
    pat_start_element_open,
    pat_end_element_open,
    pat_end_element_close,
    pat_pi_open,
    pat_pi_close,
    pat_comment,
    pat_whitespace,
    total_pattern_count
};

enum {
    sc_initial = 0,
    sc_string_quot,
    sc_string_apos,
    sc_value
};
