#include "uxs/impl/io/iobuf_impl.h"

UXS_IO_IOBUF_INSTANTIATE_IMPLEMENTATION(char);
#if UXS_USE_WCHAR_T != 0
UXS_IO_IOBUF_INSTANTIATE_IMPLEMENTATION(wchar_t);
#endif  // UXS_USE_WCHAR_T != 0
UXS_IO_IOBUF_INSTANTIATE_IMPLEMENTATION(std::uint8_t);
